TCI-80211
DEFINITIONS AUTOMATIC TAGS ::= 
BEGIN

IMPORTS
Response, 
Exception, 
MsgID FROM TCI-CommonTypes

SetInitialState, 
StartWsmTx, 
StopWsmTx, 
StartWsmRx, 
StopWsmRx  FROM TCI-wsm

Indication FROM TCI-indication
;

TCI80211 ::= CHOICE{
	request			[0]	Request,
	response		[1]	Response,
	indication 		[2] Dot11Indication,
--	responseInfo	[3]	Dot11ResponseInfo,
	exception		[4] Exception,
	...
	} 

Request ::=  SEQUENCE {
   messageId   MESSAGE-ID-AND-TYPE.&id({MessageTypes}),
   value       MESSAGE-ID-AND-TYPE.&Type({MessageTypes}{@.messageId}),
   ...
   }


MESSAGE-ID-AND-TYPE ::= CLASS {
   &id    MsgID UNIQUE,
   &Type
   } WITH SYNTAX {&Type IDENTIFIED BY &id}


MessageTypes MESSAGE-ID-AND-TYPE ::= {
-- imported from TCI-wsm
	{ SetInitialState IDENTIFIED BY setInitialState} |
	{ StartWsmTx IDENTIFIED BY startWsmTx} |
	{ StopWsmTx IDENTIFIED BY stopWsmTx} |
	{ StartWsmRx IDENTIFIED BY startWsmRx} |
	{ StopWsmRx IDENTIFIED BY stopWsmRx}
}

setInitialState     	MsgID ::= 1
startWsmTx				MsgID ::= 2
stopWsmTx				MsgID ::= 3
startWsmRx				MsgID ::= 4
stopWsmRx				MsgID ::= 5

/* 
    Request Messages

	SetInitialState, 
	SetWsmTxInfo, 
	StartWsmTx, 
	StopWsmTx, 
	StartWsmRx, 
	StopWsmRx FROM TCI-wsm

*/

Dot11Indication ::= Indication (WITH COMPONENTS {
	radio,
	event (e80211PktRx),
	eventParams	(WITH COMPONENTS {d80211frame} ) OPTIONAL,
	pdu	OPTIONAL,
	exception OPTIONAL
	})

END