TCI-ip
DEFINITIONS AUTOMATIC TAGS ::= 
BEGIN

IMPORTS
IPv6Address FROM IEEE-1609-3-WEE {iso(1) identified-organization(3) ieee(111) standards-association-numbered-series-standards(2) wave-stds(1609) dot3(3) wee(1) version0(0)}

RepeatRate, 
--IpAddress, 
IpPort, 
Opaque, 
RadioInterface FROM TCI-CommonTypes

EventHandling FROM TCI-eventHandling
;

GetIPv6InterfaceInfo ::= SEQUENCE{
	radio				RadioInterface ( WITH COMPONENTS { ..., antenna ABSENT }),
	...
}

SetIPv6Address ::= SEQUENCE{		-- WME-AddressChange.request
	radio				RadioInterface ( WITH COMPONENTS { ..., antenna ABSENT }),
	interfaceName		UTF8String(SIZE(1..255)),
	ipAddress			IPv6Address OPTIONAL, 
	-- optional if the new IPv6 address value must be selected at random
	...
}

IPv6Record ::= SEQUENCE{
	radio				RadioInterface,
	interfaceName		UTF8String(SIZE(1..255)),
	destIpAddress		IPv6Address,
	destPort			IpPort OPTIONAL,
	protocol			ENUMERATED { tcp, udp, icmp },
	repeatRate      	RepeatRate OPTIONAL,
	eventHandling       EventHandling  (WITH COMPONENTS {..., eventFlag }) OPTIONAL,
	payload		    	Opaque OPTIONAL, -- why OPTIONAL? should be present, define in profile...
	...
}

StartIPv6Tx ::= IPv6Record (WITH COMPONENTS {
	radio ( WITH COMPONENTS { ..., antenna ABSENT }),
	interfaceName,
	destIpAddress,
	destPort,
	protocol,
	repeatRate OPTIONAL,
	eventHandling OPTIONAL,
	payload PRESENT
}	
 
StopIPv6Tx ::= IPv6Record (WITH COMPONENTS {
	radio ( WITH COMPONENTS { ..., antenna ABSENT }),
	interfaceName,
	destIpAddress,
	destPort,
	protocol,
	repeatRate ABSENT,
	eventHandling ABSENT,
	payload ABSENT
})

SendIPv6Ping ::= StartIPv6Tx ( WITH COMPONENTS {
	radio,
	interfaceName,
	destIpAddress,
	destPort ABSENT,
	protocol (icmp),
	repeatRate OPTIONAL,
	eventHandling	(WITH COMPONENTS {..., eventFlag ({eIcmp6PktRx}) }),
	payload ABSENT
	})

StartIPv6Rx ::= SEQUENCE{
	radio				RadioInterface,
	interfaceName		UTF8String(SIZE(1..255)),
	listenPort			IpPort,
	protocol			ENUMERATED { tcp (0), udp (1) },
	eventHandling		EventHandling (WITH COMPONENTS {..., eventFlag ({eIpv6PktRx}) }) OPTIONAL, -- must be mandatory for Rx...
	...
}

StopIPv6Rx ::= StartIPv6Rx ( WITH COMPONENTS {
	radio ( WITH COMPONENTS { ..., antenna ABSENT }),
	interfaceName,
	listenPort,
	protocol,
	eventHandling ABSENT
})

END
