TCI-responseInfo
DEFINITIONS AUTOMATIC TAGS ::= 
BEGIN

IMPORTS
MACaddress FROM IEEE-1609-3-WEE {iso(1) identified-organization(3) ieee(111) standards-association-numbered-series-standards(2) wave-stds(1609) dot3(3) wee(1) version0(0)}

ResultCode, 
MsgID, 
Exception, 
RadioInterface, 
IpAddress, 
Opaque FROM TCI-CommonTypes
;

ResponseInfo ::= SEQUENCE {
	msgID 				MsgID,	
	resultCode			ResultCode,
	info				InfoContent	OPTIONAL, -- if exception reported, no InfoContent provided
	exception			Exception OPTIONAL,
	...
}

InfoContent::= CHOICE {
	ipv6InterfaceInfo	[1]	Ipv6InterfaceInfo,
	
	...
}

/*
	IPv6 Interface Information 
*/

Ipv6InterfaceInfo ::= SEQUENCE OF SEQUENCE {
	interfaceName		UTF8String(SIZE(1..255)),
	ipAddress			SEQUENCE OF IpAddress,
	...
}


END